image:
  registry: ghcr.io
  repository: dennybaa/test-app
service:
  ports:
    http: 3000
ingress:
  enabled: true
  hostname: test-app.dev.kube.local
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 64Mi
