app:
  name: webapp-playdemo
image:
  registry: c8n.io
  repository: dennybaa/webapp-playdemo
service:
  ports:
    http: 3000
ingress:
  enabled: true
  hostname: webapp-playdemo.dev.kube.local
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi
