app:
  name: webapp-playdemo
image:
  registry: c8n.io
  repository: dennybaa/webapp-playdemo
service:
  ports:
    http: 3000
ingress:
  enabled: true
  hostname: webapp-playdemo.prod.kube.local
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
