name: Write image version
on:
  workflow_dispatch:
    branches:
      - main

    inputs:
      yqEval:
        description: Specifies yq eval body
        required: true
      basePath:
        description: Specifies the base path to version file (test-app/dev translates to values/test-app/dev.version.yaml)
        required: true

jobs:
  write-version:
    name: Update version file
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set image version
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval -n '${{ inputs.yqEval }}' > values/${{ inputs.basePath }}.version.yaml

      -
        name: Commit updated version file
        uses: EndBug/add-and-commit@v9
        with:
          message: 'auto committed version'
          commit: --signoff
